apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  # property-like keys; each key maps to a simple value   # file-like keys
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: #THESER ARE DEPLOYMENT LEVEL LABELS
    app: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: #THESE ARE replica set LEVEL LABELS to find pods
      app: shipping
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # THESE ARE POD LABELS
        app: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: pkainnet/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
---
# shipping service is internal
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    app: shipping
    project: roboshop
    tier: app
# the following means that if someone hits the service on port 27017 , it will be redirected to container.
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 # container port

