apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  # property-like keys; each key maps to a simple value   # file-like keys
  MONGO: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels: #THESER ARE DEPLOYMENT LEVEL LABELS
    app: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: #THESE ARE replica set LEVEL LABELS to find pods
      app: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # THESE ARE POD LABELS
        app: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: pkainnet/catalogue:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue
---
# catalogue service is internal
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: app
# the following means that if someone hits the service on port 27017 , it will be redirected to container.
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 # container port

