apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: #THESER ARE DEPLOYMENT LEVEL LABELS
    app: redis
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: #THESE ARE replica set LEVEL LABELS to find pods
      app: redis
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # THESE ARE POD LABELS
        app: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
---
# redis service is internal
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    tier: db
# the following means that if someone hits the service on port 27017 , it will be redirected to container.
  ports:
  - protocol: TCP
    port: 6379 #service port
    targetPort: 6379 # container port

