apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: roboshop
data:
  # property-like keys; each key maps to a simple value   # file-like keys
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels: #THESER ARE DEPLOYMENT LEVEL LABELS
    app: web
    project: roboshop
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels: #THESE ARE replica set LEVEL LABELS to find pods
      app: web
      project: roboshop
      tier: web
  template:
    metadata:
      labels: # THESE ARE POD LABELS
        app: web
        project: roboshop
        tier: web
    spec:
      containers:
      - name: web
        image: pkainnet/web:v1
        imagePullPolicy: Always
        # envFrom:
        # - configMapRef:
        #     name: web
---
# web service is internal
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer # LoadBalancer is used to expose the service to the internet
  selector:
    app: web
    project: roboshop
    tier: web
# the following means that if someone hits the service on port 27017 , it will be redirected to container.
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port

